# Site settings
title: Лисаветин блог
email: lisavaeta.khudiakova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Lisaveta_K
github_username:  Lisaveta-K

# Build settings
markdown: kramdown
